CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Nombre] NVARCHAR(200) NOT NULL,
	[Apellido] NVARCHAR(200) NOT NULL,
	[Email] NVARCHAR(200) NOT NULL,
	[Password] NVARCHAR(200) NOT NULL,
	[CreatedDate] DATETIME DEFAULT GETDATE()
)
